name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings" # Make sure CI fails on all warnings, including Clippy lints

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        rust-version: nightly
    - uses: taiki-e/install-action@cargo-llvm-cov
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features
    - name: Collect coverage data
      run: cargo llvm-cov
